# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('phone', models.TextField()),
                ('date_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
