# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitedInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=140)),
                ('representative_name', models.CharField(max_length=100)),
                ('area_of_work', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('abbreviation', models.CharField(max_length=5)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database_Models.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('institution_benefited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database_Models.BenefitedInstitution')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Database_Models.Course')),
                ('projects_participating', models.ManyToManyField(to='Database_Models.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='volunteers_participating',
            field=models.ManyToManyField(to='Database_Models.Volunteer'),
        ),
        migrations.AddField(
            model_name='course',
            name='field_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database_Models.FieldOfStudy'),
        ),
        migrations.AddField(
            model_name='campus',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database_Models.University'),
        ),
        migrations.AddField(
            model_name='benefitedinstitution',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database_Models.ContactInstitution'),
        ),
    ]
