# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database_Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
