# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0004_auto_20170717_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field_of_study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='field_of_study',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database_models.Field_of_study'),
            preserve_default=False,
        ),
    ]
