# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0006_auto_20170717_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begins', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('date_project_begins', models.ManyToManyField(to='database_models.Date_Project')),
            ],
        ),
    ]
