# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0008_date_project_projects_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_project',
            name='projects_name',
        ),
        migrations.AddField(
            model_name='date_project',
            name='projects_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database_models.Project'),
            preserve_default=False,
        ),
    ]
