# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0009_auto_20170718_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_project',
            name='projects_name',
        ),
        migrations.AddField(
            model_name='date_project',
            name='projects_name',
            field=models.ManyToManyField(related_name='_date_project_projects_name_+', to='database_models.Project'),
        ),
    ]
