# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0010_auto_20170718_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='volunteers_participating',
            field=models.ManyToManyField(to='database_models.Volunteer'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='projects_participating',
            field=models.ManyToManyField(to='database_models.Project'),
        ),
    ]
