# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0011_auto_20170718_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_project',
            name='projects_name',
            field=models.ManyToManyField(to='database_models.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='volunteers_participating',
            field=models.ManyToManyField(null=True, to='database_models.Volunteer'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='projects_participating',
            field=models.ManyToManyField(null=True, to='database_models.Project'),
        ),
    ]
