# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0012_auto_20170718_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitedInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=140)),
                ('representative_name', models.CharField(max_length=100)),
                ('area_of_work', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.RenameModel(
            old_name='Date_Project',
            new_name='DateProject',
        ),
        migrations.RenameModel(
            old_name='Field_of_study',
            new_name='FieldOfStudy',
        ),
        migrations.AlterField(
            model_name='project',
            name='volunteers_participating',
            field=models.ManyToManyField(to='database_models.Volunteer'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='projects_participating',
            field=models.ManyToManyField(to='database_models.Project'),
        ),
        migrations.AddField(
            model_name='benefitedinstitution',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.ContactInstitution'),
        ),
        migrations.AddField(
            model_name='project',
            name='institution_benefited',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database_models.BenefitedInstitution'),
            preserve_default=False,
        ),
    ]
